version: 2
jobs:
  test:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run: npm install
    - run: sudo npm i -g nyc codecov
    - run:
        name: Test
        command: npm test
    - run:
        name: Generate code coverage
        command: nyc report --reporter=lcov > coverage.lcov && codecov

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
